import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Providers from "@/components/providers";
import Header from "@/components/layout/header";

const sarabun = Sarabun({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-sarabun",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sarabun.variable} suppressHydrationWarning>
      <body>
        <Providers>
          {/* Header  */}
          <Header />

          {/* Content */}
          {children}
        </Providers>

        {/* Sonner */}
        <Toaster />
      </body>
    </html>
  );
}
