import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { Sarabun, Zain } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/providers";
import MainHeader from "@/components/layout/header/components/main-header";
import NavigationHeader from "@/components/layout/header/components/navigation-header";
import Footer from "@/components/layout/footer";

const sarabun = Sarabun({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-sarabun",
  display: "swap",
});

const zain = Zain({
  subsets: ["latin"],
  weight: ["700", "400", "300"],
  variable: "--font-zain",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      suppressHydrationWarning
      lang={locale}
      className={locale === "ar" ? zain.variable : sarabun.variable}
      dir={locale === "ar" ? "rtl" : "ltr"}
    >
      <body>
        <Providers>
          {/* Main Header */}
          <MainHeader />

          {/* Navigation Header */}
          <NavigationHeader />

          {/* Main Content */}
          {children}

          {/* Footer */}
          <Footer />

          {/* Toaster */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
