import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { Sarabun, Tajawal } from "next/font/google";
import localFont from "next/font/local";
import Providers from "@/components/providers";

const sarabun = Sarabun({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-sarabun",
  display: "swap",
});

const tajawal = Tajawal({
  subsets: ["latin"],
  weight: ["700", "400", "300"],
  variable: "--font-tajawal",
});

const diwany = localFont({
  src: "../fonts/diwany/diwany.ttf",
  variable: "--font-diwany",
  display: "swap",
});

const edwiardian = localFont({
  src: "../fonts/edwiardian/edwardianscriptitc.ttf",
  display: "swap",
  variable: "--font-edwiardian",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      suppressHydrationWarning
      lang={locale}
      className={` ${locale === "ar" ? tajawal.variable : sarabun.variable} ${diwany.variable} ${
        edwiardian.variable
      }`}
      dir={locale === "ar" ? "rtl" : "ltr"}
    >
      <body>
        <Providers>
          {/* Main Content */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
